Add files via upload
Radoslava486/ShareLane_Rada_Mishurova pull request #1
Opened 2022-06-29 10:54 UTC by Radoslava486

2022-06-29 11:52 UTC, voropa requested changes

2022-06-29 11:52 UTC, voropa commented on SignUpTestsMishurova.java
> +    @Before
These are JUnit annotations but we're using TestNG framework
please replace them with @BeforeClass @AfterClass imported from org.testng library

2022-06-29 13:31 UTC, Radoslava486 commented on SignUpTestsMishurova.java
> +    @Before
Хорошо, а с этим что? 
![image](https://user-images.githubusercontent.com/108293735/176448743-0840ca12-8503-450a-a733-bf2aba6b4682.png)

2022-06-29 13:42 UTC, voropa requested changes

2022-06-29 13:42 UTC, voropa commented on SignUpTestsMishurova.java
> +    private WebDriverManager driver;
тут должен быть обьявлен WebDriver driver, а не WebdriverManager

2022-06-29 13:42 UTC, voropa commented on SignUpTestsMishurova.java
> +        WebDriver driver = new ChromeDriver();
А вот тут должен быть проинициализирован обьект driver, который мы обьявили как поле (атрибут) класса, чтобы дотсуп к этому обьекту был у всех методов класса.
Т.е. тут должно быть так: driver = new ChromeDriver();

2022-06-30 08:18 UTC, voropa requested changes

2022-06-30 08:18 UTC, voropa commented on SignUpTestsMishurova.java
>          driver.manage().window().maximize();
Please add implicity wait 5s here

2022-06-30 08:18 UTC, voropa commented on SignUpTestsMishurova.java
> +        Assert.assertTrue(driver.findElement(By.xpath("//*[text()=‘War and Peace’]")).isDisplayed(), " Relevant books should be displayed " );
Use programming quotes ' in locators instead of grammatical one ’
Programming code doesn't work with grammatical quotes.
And there should be a space at the end of the book name, thats why your locator doesn't find any element:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/14195681/176628286-ee184494-fe9e-44d4-bb69-7ed8669d4ca8.png">

2022-06-30 08:18 UTC, voropa commented on SignUpTestsMishurova.java
> +        Assert.assertTrue(driver.findElement(By.xpath("//*[text()=‘Leo Tolstoy’]")).isDisplayed(), " Relevant books should be displayed " );
Same for quotes

2022-07-05 07:44 UTC, voropa approved these changes

2022-07-14 13:26 UTC, merged